classDiagram
  class run_indexer {
  }
  class run_pipeline {
  }
  class run_eval {
  }
  class config {
  }
  class pipeline {
  }
  class retriever {
  }
  class reranker {
  }
  class service_predictor {
  }
  class evaluator {
  }
  class indexer {
  }
  class query_writer {
  }
  run_indexer --> indexer
  run_indexer --> config
  run_pipeline --> pipeline
  run_pipeline --> config
  run_eval --> pipeline
  run_eval --> evaluator
  run_eval --> config
  pipeline --> query_writer
  pipeline --> reranker
  pipeline --> retriever
  pipeline --> service_predictor
  pipeline --> config
  indexer --> config
  retriever --> config
  reranker --> config
  service_predictor --> config
  evaluator --> config
  query_writer --> config
